[tool.poetry]
name = "noteable_magics"
version = "0.2.0"
description = "IPython Magics for Noteable"
authors = ["Eli Wilson <eli@noteable.io>"]

[tool.poetry.dependencies]
python = "^3.8"
ipython = "7.20.0"
pandas = "^1.2.3"
xlrd = "^2.0.1"
openpyxl = "^3.0.7"
pyarrow = "^3.0.0"
ipython-sql = "^0.4.0"
click = "^7.1.2"
redis = "^3.5.3"
pydantic = "^1.8.1"
GitPython = "^3.1.14"
protobuf = "^3.15.6"
backoff = "^1.10.0"
rich = "^10.1.0"
unidiff = "^0.6.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.8.0"
flake8 = "^3.9.0"
notebook = "^6.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
skip-string-normalization = true

[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
known_third_party = ["nbformat"]
